# Basics
DefaultContentLanguage = "en"
title = "Rouke Broersma"
theme = "beautifulhugo"
summarylength = 10

# Build options
publishdir = "/dist"
canonifyURLs = true
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
