# Basics
baseUrl = "https://broersma.dev"
title = "Rouke's Blog"
DefaultContentLanguage = "en"
theme = "beautifulhugo"

# Build options
publishdir = "/dist"
canonifyURLs = true
enableGitInfo = true
enableEmoji = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
