# Basics
baseUrl = "https://broersma.dev"
DefaultContentLanguage = "en"
theme = "beautifulhugo"

# Build options
publishdir = "/dist"
canonifyURLs = true
enableGitInfo = true
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-38790437-4"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
